### ISSUE TITLE
User can view a list of Studio Ghibli films

### ISSUE THREAD

**Issue by ashleyavena** [ashleyavena/front-end-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### Display and use the navigation bar to toggle through different pages, and search by names or director for films.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![user can view a list of Studio Ghibli films on mobile]
<img width="145" alt="Screenshot 2024-12-03 at 1 45 02 PM" src="https://github.com/user-attachments/assets/a7d5ea80-b3b5-4ed1-a37a-98a45a6e8d6d">

![user can view a list of Studio Ghibli films desktop]
<img width="483" alt="Screenshot 2024-12-03 at 1 44 58 PM" src="https://github.com/user-attachments/assets/0a620f8e-cc31-4178-9711-1dc2d18adcb2">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x]  HTML skeleton that matches figma
 - [x]  CSS for skeleton elements
 - [x] * Complete the HTML form using the appropriate responsive layout classes.
    *  Write CSS for mobile devices first.
    *  Adjust styling to fluidly adapt to desktop.
- [x]   Add a div [data-view= 'navBar'] to the html
- [x]  Add an unordered list containing all navBar elements in html
- [x]  Add navigation items to the navigation bar unordered list for all clickable items by adding anchor attributes
- [x]  Create a search bar within the navigation bar
- [x]  Add background photos and text layout on html & CSS
- [x]  Format in CSS for appropriate media dimensions
 - [x]  API call for film data
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
